/*
 *
 * Cv constants
 *
 */

export const LOAD_PUBLIC_INFO = 'app/Cv/LOAD_PUBLIC_INFO';
export const LOAD_PUBLIC_INFO_SUCCESS = 'app/Cv/LOAD_PUBLIC_INFO_SUCCESS';
export const LOAD_PUBLIC_INFO_ERROR = 'app/Cv/LOAD_PUBLIC_INFO_ERROR';
export const LOAD_EDUCATIONS = 'app/Cv/LOAD_EDUCATIONS';
export const LOAD_EDUCATIONS_SUCCESS = 'app/Cv/LOAD_EDUCATIONS_SUCCESS';
export const LOAD_EDUCATIONS_ERROR = 'app/Cv/LOAD_EDUCATIONS_ERROR';
export const LOAD_EXPERIENCES = 'app/Cv/LOAD_EXPERIENCES';
export const LOAD_EXPERIENCES_SUCCESS = 'app/Cv/LOAD_EXPERIENCES_SUCCESS';
export const LOAD_EXPERIENCES_ERROR = 'app/Cv/LOAD_EXPERIENCES_ERROR';
export const LOAD_LANGUAGE_SKILLS = 'app/Cv/LOAD_LANGUAGE_SKILLS';
export const LOAD_LANGUAGE_SKILLS_SUCCESS =
  'app/Cv/LOAD_LANGUAGE_SKILLS_SUCCESS';
export const LOAD_LANGUAGE_SKILLS_ERROR = 'app/Cv/LOAD_LANGUAGE_SKILLS_ERROR';
export const LOAD_OTHER_INTERESTS = 'app/Cv/LOAD_OTHER_INTERESTS';
export const LOAD_OTHER_INTERESTS_SUCCESS =
  'app/Cv/LOAD_OTHER_INTERESTS_SUCCESS';
export const LOAD_OTHER_INTERESTS_ERROR = 'app/Cv/LOAD_OTHER_INTERESTS_ERROR';
export const LOAD_PROFESSIONAL_SKILLS = 'app/Cv/LOAD_PROFESSIONAL_SKILLS';
export const LOAD_PROFESSIONAL_SKILLS_SUCCESS =
  'app/Cv/LOAD_PROFESSIONAL_SKILLS_SUCCESS';
export const LOAD_PROFESSIONAL_SKILLS_ERROR =
  'app/Cv/LOAD_PROFESSIONAL_SKILLS_ERROR';
